### PR TITLE
add pre-approved projects list

### PR DESCRIPTION
**Pull request by kungfuchicken**
This is the list of projects that are pre-approved for getting extra credit. If a patch is fully merged into one of these repos you can get full credit for any assignment.

### CODE REVIEW

**Review by kungfuchicken — COMMENTED** [review]
lgtm;

**Comment by vakhil-98** [comment]
Thanks for the list :)

**Review by AbhilashKotha — APPROVED** [review]
lgtm; Thanks for these extra credit options;

**Comment by AbhilashKotha** [comment]
I have approved the changes. You can proceed with the merge.

**Pull request merged**
